#############################################################################
# Makefile for building: TelegramBB10
# Generated by qmake (2.01a) (Qt 4.8.6) on: Wed 2. Sep 22:46:42 2026
# Project:  TelegramBB10.pro
# Template: app
# Command: c:/bbndk_api/host_10_3_1_12/win32/x86/usr/bin/qmake.exe -spec c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/blackberry-armv7le-qcc CONFIG+=release CONFIG+=device -o Makefile TelegramBB10.pro
#############################################################################

####### Compiler, tools and options

CC            = qcc -Vgcc_ntoarmv7le
CXX           = qcc -Vgcc_ntoarmv7le
DEFINES       = -DQT_NO_IMPORT_QT47_QML -DQ_OS_BLACKBERRY -D_FORTIFY_SOURCE=2 -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_SCRIPT_LIB -DQT_SVG_LIB -DQT_SQL_LIB -DQT_XMLPATTERNS_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -Wno-psabi -fstack-protector -fstack-protector-all -mcpu=cortex-a9 -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -O2 -Wno-psabi -fstack-protector-strong -fvisibility=hidden -mthumb -Os -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -Wno-psabi -lang-c++ -fstack-protector -fstack-protector-all -mcpu=cortex-a9 -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -O2 -Wno-psabi -fstack-protector-strong -fvisibility=hidden -mthumb -Os -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -Ic:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/blackberry-armv7le-qcc -I. -Ic:/bbndk_api/target_10_3_1_995/qnx6/usr/include/qt4/QtCore -Ic:/bbndk_api/target_10_3_1_995/qnx6/usr/include/qt4/QtNetwork -Ic:/bbndk_api/target_10_3_1_995/qnx6/usr/include/qt4/QtGui -Ic:/bbndk_api/target_10_3_1_995/qnx6/usr/include/qt4/QtXml -Ic:/bbndk_api/target_10_3_1_995/qnx6/usr/include/qt4/QtXmlPatterns -Ic:/bbndk_api/target_10_3_1_995/qnx6/usr/include/qt4/QtSql -Ic:/bbndk_api/target_10_3_1_995/qnx6/usr/include/qt4/QtSvg -Ic:/bbndk_api/target_10_3_1_995/qnx6/usr/include/qt4/QtScript -Ic:/bbndk_api/target_10_3_1_995/qnx6/usr/include/qt4/QtDeclarative -Ic:/bbndk_api/target_10_3_1_995/qnx6/usr/include/qt4 -Isrc -Isrc/crypto -Isrc/tl -Isrc/network -Isrc/core -Isrc/storage -Isrc/controllers -Isrc/models -I. -Ic:/bbndk_api/target_10_3_1_995/qnx6/usr/include/bb1 -Ic:/bbndk_api/target_10_3_1_995/qnx6/usr/include -Ic:/bbndk_api/target_10_3_1_995/qnx6/usr/include/freetype2
LINK          = qcc -Vgcc_ntoarmv7le
LFLAGS        = -lang-c++ -Wl,-rpath-link,c:\bbndk_api\target_10_3_1_995\qnx6/armle-v7/lib -Wl,-rpath-link,c:\bbndk_api\target_10_3_1_995\qnx6/armle-v7/usr/lib -Wl,-rpath-link,c:\bbndk_api\target_10_3_1_995\qnx6/armle-v7/usr/lib/qt4/lib -Wl,-O1 -Wl,-z,relro
LIBS          = $(SUBLIBS)  -Lc:\bbndk_api\target_10_3_1_995\qnx6/armle-v7/usr/lib/bb1 -Lc:\bbndk_api\target_10_3_1_995\qnx6/armle-v7/lib -Lc:\bbndk_api\target_10_3_1_995\qnx6/armle-v7/usr/lib -Lc:\bbndk_api\target_10_3_1_995\qnx6/armle-v7/usr/lib/qt4/lib -Lc:\bbndk_api\target_10_3_1_995\qnx6//usr/lib/qt4/lib -lcrypto -lssl -lbb -lbbcascades -lQtDeclarative -lQtScript -lQtSvg -lQtSql -lsqlite3 -lz -lQtXmlPatterns -lQtXml -lQtGui -lQtNetwork -lsocket -lQtCore -lm -lbps 
AR            = ntoarmv7-ar cqs
RANLIB        = ntoarmv7-ranlib
QMAKE         = c:/bbndk_api/host_10_3_1_12/win32/x86/usr/bin/qmake.exe
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = ntoarmv7-strip
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/Config.cpp \
		src/crypto/CryptoEngine.cpp \
		src/crypto/qrcodegen.cpp \
		src/crypto/QrGenerator.cpp \
		src/tl/TLBuffer.cpp \
		src/network/TcpTransport.cpp \
		src/core/MTProtoSession.cpp \
		src/storage/SessionStorage.cpp \
		src/controllers/DiagnosticController.cpp \
		src/controllers/AuthController.cpp \
		src/models/DialogItem.cpp \
		src/controllers/ChatListController.cpp moc_TcpTransport.cpp \
		moc_MTProtoSession.cpp \
		moc_SessionStorage.cpp \
		moc_DiagnosticController.cpp \
		moc_AuthController.cpp \
		moc_ChatListController.cpp
OBJECTS       = main.o \
		Config.o \
		CryptoEngine.o \
		qrcodegen.o \
		QrGenerator.o \
		TLBuffer.o \
		TcpTransport.o \
		MTProtoSession.o \
		SessionStorage.o \
		DiagnosticController.o \
		AuthController.o \
		DialogItem.o \
		ChatListController.o \
		moc_TcpTransport.o \
		moc_MTProtoSession.o \
		moc_SessionStorage.o \
		moc_DiagnosticController.o \
		moc_AuthController.o \
		moc_ChatListController.o
DIST          = c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/common/g++-base.conf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/common/g++-unix.conf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/common/unix.conf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/common/qcc-base.conf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/common/qcc-base-qnx.conf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/qconfig.pri \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/qt_functions.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/qt_config.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/qnx-armv7le-qcc/qmake.conf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/default_pre.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/release.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/default_post.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/cascades.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/shared.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/warn_on.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/qt.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/unix/thread.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/moc.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/resources.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/uic.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/yacc.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/lex.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		TelegramBB10.pro
QMAKE_TARGET  = TelegramBB10
DESTDIR       = 
TARGET        = TelegramBB10

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TelegramBB10.pro  c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/blackberry-armv7le-qcc/qmake.conf c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/common/g++-base.conf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/common/g++-unix.conf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/common/unix.conf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/common/qcc-base.conf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/common/qcc-base-qnx.conf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/qconfig.pri \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/qt_functions.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/qt_config.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/qnx-armv7le-qcc/qmake.conf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/default_pre.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/release.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/default_post.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/cascades.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/shared.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/warn_on.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/qt.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/unix/thread.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/moc.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/resources.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/uic.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/yacc.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/lex.prf \
		c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtDeclarative.prl \
		c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtScript.prl \
		c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtCore.prl \
		c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtSvg.prl \
		c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtGui.prl \
		c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtSql.prl \
		c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtXmlPatterns.prl \
		c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtNetwork.prl \
		c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtXml.prl
	$(QMAKE) -spec c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/blackberry-armv7le-qcc CONFIG+=release CONFIG+=device -o Makefile TelegramBB10.pro
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/common/g++-base.conf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/common/g++-unix.conf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/common/unix.conf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/common/qcc-base.conf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/common/qcc-base-qnx.conf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/qconfig.pri:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/qt_functions.prf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/qt_config.prf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/qnx-armv7le-qcc/qmake.conf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/default_pre.prf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/release.prf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/default_post.prf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/cascades.prf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/shared.prf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/warn_on.prf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/qt.prf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/unix/thread.prf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/moc.prf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/resources.prf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/uic.prf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/yacc.prf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/lex.prf:
c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/features/include_source_dir.prf:
c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtDeclarative.prl:
c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtScript.prl:
c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtCore.prl:
c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtSvg.prl:
c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtGui.prl:
c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtSql.prl:
c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtXmlPatterns.prl:
c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtNetwork.prl:
c:\bbndk_api\target_10_3_1_995\qnx6\armle-v7\usr\lib\qt4\lib\libQtXml.prl:
qmake:  FORCE
	@$(QMAKE) -spec c:/bbndk_api/target_10_3_1_995/qnx6/usr/share/qt4/mkspecs/blackberry-armv7le-qcc CONFIG+=release CONFIG+=device -o Makefile TelegramBB10.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/TelegramBB101.0.0 || $(MKDIR) .tmp/TelegramBB101.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TelegramBB101.0.0/ && $(COPY_FILE) --parents src/Config.h src/crypto/CryptoEngine.h src/crypto/qrcodegen.h src/crypto/QrGenerator.h src/tl/TLBuffer.h src/tl/TLTypes.h src/network/TcpTransport.h src/core/MTProtoSession.h src/storage/SessionStorage.h src/controllers/DiagnosticController.h src/controllers/AuthController.h src/models/DialogItem.h src/controllers/ChatListController.h .tmp/TelegramBB101.0.0/ && $(COPY_FILE) --parents src/main.cpp src/Config.cpp src/crypto/CryptoEngine.cpp src/crypto/qrcodegen.cpp src/crypto/QrGenerator.cpp src/tl/TLBuffer.cpp src/network/TcpTransport.cpp src/core/MTProtoSession.cpp src/storage/SessionStorage.cpp src/controllers/DiagnosticController.cpp src/controllers/AuthController.cpp src/models/DialogItem.cpp src/controllers/ChatListController.cpp .tmp/TelegramBB101.0.0/ && (cd `dirname .tmp/TelegramBB101.0.0` && $(TAR) TelegramBB101.0.0.tar TelegramBB101.0.0 && $(COMPRESS) TelegramBB101.0.0.tar) && $(MOVE) `dirname .tmp/TelegramBB101.0.0`/TelegramBB101.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TelegramBB101.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_TcpTransport.cpp moc_MTProtoSession.cpp moc_SessionStorage.cpp moc_DiagnosticController.cpp moc_AuthController.cpp moc_ChatListController.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_TcpTransport.cpp moc_MTProtoSession.cpp moc_SessionStorage.cpp moc_DiagnosticController.cpp moc_AuthController.cpp moc_ChatListController.cpp
moc_TcpTransport.cpp: src/network/TcpTransport.h
	c:/bbndk_api/host_10_3_1_12/win32/x86/usr/bin/moc.exe $(DEFINES) $(INCPATH) -D__QNXNTO__ src/network/TcpTransport.h -o moc_TcpTransport.cpp

moc_MTProtoSession.cpp: src/core/MTProtoSession.h
	c:/bbndk_api/host_10_3_1_12/win32/x86/usr/bin/moc.exe $(DEFINES) $(INCPATH) -D__QNXNTO__ src/core/MTProtoSession.h -o moc_MTProtoSession.cpp

moc_SessionStorage.cpp: src/storage/SessionStorage.h
	c:/bbndk_api/host_10_3_1_12/win32/x86/usr/bin/moc.exe $(DEFINES) $(INCPATH) -D__QNXNTO__ src/storage/SessionStorage.h -o moc_SessionStorage.cpp

moc_DiagnosticController.cpp: src/controllers/DiagnosticController.h
	c:/bbndk_api/host_10_3_1_12/win32/x86/usr/bin/moc.exe $(DEFINES) $(INCPATH) -D__QNXNTO__ src/controllers/DiagnosticController.h -o moc_DiagnosticController.cpp

moc_AuthController.cpp: src/controllers/AuthController.h
	c:/bbndk_api/host_10_3_1_12/win32/x86/usr/bin/moc.exe $(DEFINES) $(INCPATH) -D__QNXNTO__ src/controllers/AuthController.h -o moc_AuthController.cpp

moc_ChatListController.cpp: src/controllers/ChatListController.h
	c:/bbndk_api/host_10_3_1_12/win32/x86/usr/bin/moc.exe $(DEFINES) $(INCPATH) -D__QNXNTO__ src/controllers/ChatListController.h -o moc_ChatListController.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src\core\MTProtoSession.h \
		src\storage\SessionStorage.h \
		src\controllers\DiagnosticController.h \
		src\controllers\AuthController.h \
		src\controllers\ChatListController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

Config.o: src/Config.cpp src\Config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Config.o src/Config.cpp

CryptoEngine.o: src/crypto/CryptoEngine.cpp src\crypto\CryptoEngine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CryptoEngine.o src/crypto/CryptoEngine.cpp

qrcodegen.o: src/crypto/qrcodegen.cpp src\crypto\qrcodegen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrcodegen.o src/crypto/qrcodegen.cpp

QrGenerator.o: src/crypto/QrGenerator.cpp src\crypto\QrGenerator.h \
		src\crypto\qrcodegen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QrGenerator.o src/crypto/QrGenerator.cpp

TLBuffer.o: src/tl/TLBuffer.cpp src\tl\TLBuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TLBuffer.o src/tl/TLBuffer.cpp

TcpTransport.o: src/network/TcpTransport.cpp src\network\TcpTransport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TcpTransport.o src/network/TcpTransport.cpp

MTProtoSession.o: src/core/MTProtoSession.cpp src\core\MTProtoSession.h \
		src\models\DialogItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MTProtoSession.o src/core/MTProtoSession.cpp

SessionStorage.o: src/storage/SessionStorage.cpp src\storage\SessionStorage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SessionStorage.o src/storage/SessionStorage.cpp

DiagnosticController.o: src/controllers/DiagnosticController.cpp src\controllers\DiagnosticController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DiagnosticController.o src/controllers/DiagnosticController.cpp

AuthController.o: src/controllers/AuthController.cpp src\controllers\AuthController.h \
		src\core\MTProtoSession.h \
		src\storage\SessionStorage.h \
		src\crypto\QrGenerator.h \
		src\Config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AuthController.o src/controllers/AuthController.cpp

DialogItem.o: src/models/DialogItem.cpp src\models\DialogItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DialogItem.o src/models/DialogItem.cpp

ChatListController.o: src/controllers/ChatListController.cpp src\controllers\ChatListController.h \
		src\core\MTProtoSession.h \
		src\storage\SessionStorage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChatListController.o src/controllers/ChatListController.cpp

moc_TcpTransport.o: moc_TcpTransport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TcpTransport.o moc_TcpTransport.cpp

moc_MTProtoSession.o: moc_MTProtoSession.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MTProtoSession.o moc_MTProtoSession.cpp

moc_SessionStorage.o: moc_SessionStorage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SessionStorage.o moc_SessionStorage.cpp

moc_DiagnosticController.o: moc_DiagnosticController.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DiagnosticController.o moc_DiagnosticController.cpp

moc_AuthController.o: moc_AuthController.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AuthController.o moc_AuthController.cpp

moc_ChatListController.o: moc_ChatListController.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ChatListController.o moc_ChatListController.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

